Starting Debug for lxc1-0
Running Command /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/run.sh -e 0 --node 1 /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/modbus/simple_client_server_multiple/sfb102_client.awl
6 (process ID) old priority 0, new priority 10
=== Running tests with 'python2'
Running test 'sfb102_client.awl' with 'python2' ... [u'0', u'10.10.0.9']
[u'1', u'10.10.0.10']
[u'IDS', u'10.10.0.10']
('Dest IP : ', '10.10.0.17')
('Resolved hostname = ', '10.10.0.17')
('IP of IDS : ', '10.10.0.25', ' len = ', 10, ' orig_len = ', 10)
('Start time = ', 1460597382.785201)
('IP:PORT = ', '10.10.0.17', 502)
('10.10.0.17', 502)
[Errno 111] Connection refused
('Start time = ', 1460597382.818787)
('IP:PORT = ', '10.10.0.17', 502)
Resumed connection
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/systemblocks/test_run.py", line 334, in test_run_client_ip
    recv_time = datetime.datetime,now()
NameError: global name 'now' is not defined
('Sent msg = ', bytearray(b'\x00\x10\x03\x00\x02\x00\x01\x16'))
